print("========================================")
print("         My python profile")
print("========================================")
print("Name : Nipuna Madhuranga")
print("Studnet ID : 232089")
print("Degree : JM (CM+ELTN)")
print("University : Wayamba University")
print("I am learning Python")
print("I'm intereseted in compiler Design")
print("This is my first python practical")